# Generated by Django 4.1.7 on 2023-02-28 10:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_userinfo_followers_alter_userinfo_followings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=100000)),
                ('createdTime', models.DateTimeField(default=datetime.datetime(2023, 2, 28, 16, 19, 2, 879241))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
